service telnet-23
{
    type         = UNLISTED
    port         = 23
    socket_type  = stream
    protocol     = tcp
    wait         = no
    user         = root
    server       = /usr/sbin/in.telnetd
    server_args  = -L /bin/login
    disable      = no
}
