#!/usr/bin/env python3
"""Emit docs/wiki/ANEXO-INDICE-MODULOS.md from live index_modules()."""

from __future__ import annotations

# Author: André Henrique (@mrhenrike) | União Geek — https://github.com/Uniao-Geek

import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from embedxpl.core.exploit.utils import humanize_path, index_modules


def main() -> int:
    """Write markdown annex; return 0."""
    repo_root = Path(__file__).resolve().parents[1]
    out = repo_root / "docs" / "wiki" / "ANEXO-INDICE-MODULOS.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Module path index / Índice de caminhos de módulos",
        "",
        "**Language-neutral list.** Regenerated by `tools/gen_wiki_module_index.py` from `index_modules()`.",
        "**Lista neutra quanto ao idioma.** Regenerada por `tools/gen_wiki_module_index.py` a partir de `index_modules()`.",
        "",
        "**Usage guides:** [en-US](en-US/README.md) · [pt-BR](pt-BR/README.md)",
        "",
    ]
    paths = sorted(index_modules())
    for mod in paths:
        lines.append("- `{}`".format(humanize_path(mod)))
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    print("wrote {} modules -> {}".format(len(paths), out.as_posix()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
