"""Quality gate system for EmbedXPL-Forge integration phases.

Each gate verifies a set of module files are fully implemented,
importable, structurally correct, and free of prohibited patterns
before allowing progression to the next development step.

All checks are automated. No manual review items exist.
Exit code 0 = gate passed. Exit code 1 = gate failed.

Author: André Henrique (@mrhenrike) | União Geek - https://github.com/Uniao-Geek
"""

from __future__ import annotations

import argparse
import ast
import importlib
import os
import re
import socket
import subprocess
import sys
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Tuple

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

BASELINE_MODULE_COUNT = 2738

# Patterns that must never appear in module source
_PROHIBITED_STRINGS = [
    "\u2014",            # em dash
    "TODO",
    "FIXME",
    "PLACEHOLDER",
    "raise NotImplementedError",
    "generated by",
    "created with AI",
    "AI note",
    "LLM suggestion",
    "Cursor",
]

_PROHIBITED_PATTERNS_CODE = [
    r"^pass\s*#",           # pass with inline comment
    r"^\s*pass\s*$",        # standalone pass in check/run body
]

_LAB_IP_RE = re.compile(
    r"\b(10\.\d+\.\d+\.\d+|192\.168\.\d+\.\d+|172\.(1[6-9]|2\d|3[01])\.\d+\.\d+)\b"
)

_URL_RE = re.compile(r"https?://\S+")

_CVSS_RE = re.compile(
    r"^(\d+\.\d+|CVSS:3\.[01]/AV:[NALP]/AC:[LH]/PR:[NLH]/UI:[NR]/S:[UC]/C:[NLH]/I:[NLH]/A:[NLH])$"
)


# ─── Result dataclass ─────────────────────────────────────────────────────────

@dataclass
class CheckResult:
    name: str
    passed: bool
    message: str = ""


def _ok(name: str, msg: str = "") -> CheckResult:
    return CheckResult(name=name, passed=True, message=msg)


def _fail(name: str, msg: str) -> CheckResult:
    return CheckResult(name=name, passed=False, message=msg)


# ─── Shared helpers ───────────────────────────────────────────────────────────

def _read_file(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return ""


def _run_python(snippet: str, timeout: int = 10) -> Tuple[bool, str]:
    """Run a Python snippet via subprocess and return (success, output)."""
    try:
        proc = subprocess.run(
            [sys.executable, "-c", snippet],
            capture_output=True, text=True, timeout=timeout,
            cwd=str(ROOT),
            env={**os.environ, "PYTHONPATH": str(ROOT), "PYTHONUTF8": "1"},
        )
        if proc.returncode == 0:
            return True, proc.stdout.strip()
        return False, (proc.stderr or proc.stdout).strip()
    except subprocess.TimeoutExpired:
        return False, "timeout"
    except Exception as e:
        return False, str(e)


def _run_python_file(script: str, timeout: int = 15) -> Tuple[bool, str]:
    """Write script to a temp file and run it."""
    tmp_dir = ROOT / ".tmp"
    tmp_dir.mkdir(exist_ok=True)
    tmp_file = tmp_dir / f"gate_check_{os.getpid()}_{int(time.time()*1000)}.py"
    header = f"import sys; sys.path.insert(0, {str(ROOT)!r})\n"
    tmp_file.write_text(header + script, encoding="utf-8")
    try:
        proc = subprocess.run(
            [sys.executable, str(tmp_file)],
            capture_output=True, text=True, timeout=timeout,
            cwd=str(ROOT),
            env={**os.environ, "PYTHONPATH": str(ROOT), "PYTHONUTF8": "1"},
        )
        ok = proc.returncode == 0
        out = proc.stdout.strip() if ok else (proc.stderr or proc.stdout).strip()
        return ok, out
    except subprocess.TimeoutExpired:
        return False, "timeout"
    except Exception as e:
        return False, str(e)
    finally:
        try:
            tmp_file.unlink(missing_ok=True)
        except Exception:
            pass


# ─── Common module checks (applied to every new module) ──────────────────────

def _common_module_checks(paths: List[Path]) -> List[CheckResult]:
    """Apply standard checks to a list of module paths."""
    results: List[CheckResult] = []

    for path in paths:
        name = path.stem

        # 1. File exists
        if not path.exists():
            results.append(_fail(f"exists:{name}", f"File not found: {path}"))
            continue

        src = _read_file(path)

        # 2. Has class Exploit
        if "class Exploit" not in src:
            results.append(_fail(f"class_exploit:{name}", f"{path.name}: no class Exploit"))
            continue

        # 3. __info__ with required keys
        for key in ("name", "description", "authors", "references", "devices"):
            if f'"{key}"' not in src and f"'{key}'" not in src:
                results.append(_fail(f"info_{key}:{name}", f"{path.name}: __info__ missing '{key}'"))

        # 4. references has at least one https:// URL
        ref_match = re.search(r"['\"]references['\"].*?(\(.*?\)|\[.*?\])", src, re.S)
        if ref_match:
            ref_block = ref_match.group(0)
            if "https://" not in ref_block and "http://" not in ref_block:
                results.append(_fail(f"references_url:{name}", f"{path.name}: __info__['references'] has no URL"))
        else:
            results.append(_fail(f"references_url:{name}", f"{path.name}: could not parse references field"))

        # 5. check() and run() exist with a body
        for method in ("check", "run"):
            pattern = rf"def {method}\s*\("
            if not re.search(pattern, src):
                results.append(_fail(f"{method}_exists:{name}", f"{path.name}: missing def {method}()"))
            else:
                # Ensure body is not just 'pass' or 'return'
                m = re.search(rf"def {method}\s*\([^)]*\)[^:]*:(.*?)(?=\ndef |\Z)", src, re.S)
                if m:
                    body = m.group(1).strip()
                    stripped = re.sub(r"#.*$", "", body, flags=re.M).strip()
                    if stripped in ("", "pass", "..."):
                        results.append(_fail(f"{method}_body:{name}", f"{path.name}: {method}() is a stub (empty body)"))

        # 6. No prohibited strings
        for prohibited in _PROHIBITED_STRINGS:
            if prohibited in src:
                results.append(_fail(f"prohibited:{name}", f"{path.name}: contains prohibited string '{prohibited[:30]}'"))

        # 7. No hardcoded lab IPs (except in comments or __info__)
        src_no_comments = re.sub(r"#.*$", "", src, flags=re.M)
        src_no_info = re.sub(r"__info__.*?^\s*\}", "", src_no_comments, flags=re.M | re.S)
        lab_ips = _LAB_IP_RE.findall(src_no_info)
        # Allow 192.168.x.x only in OptIP defaults and examples
        real_lab_ips = [ip for ip in lab_ips if ip not in ("192.168.1.1", "192.168.0.1", "192.168.1.100", "10.0.0.1")]
        if real_lab_ips:
            results.append(_fail(f"lab_ip:{name}", f"{path.name}: hardcoded lab IPs: {real_lab_ips[:3]}"))

        # 8. No subprocess for external tools (only socket/requests/http_client allowed)
        if re.search(r"\bsubprocess\b|\bos\.system\b|\bshlex\b", src):
            # Allow if used in bridge modules only
            if "bridge" not in name and "_bridge" not in str(path):
                results.append(_fail(f"no_subprocess:{name}", f"{path.name}: uses subprocess (not allowed in non-bridge modules)"))

    return results


def _check_importable(paths: List[Path]) -> List[CheckResult]:
    """Verify each module can be imported without error."""
    results: List[CheckResult] = []
    for path in paths:
        if not path.exists():
            continue
        dotted = (
            "embedxpl.modules."
            + str(path.relative_to(ROOT / "embedxpl" / "modules"))
            .replace(os.sep, ".")
            .removesuffix(".py")
        )
        script = (
            f"import warnings; warnings.filterwarnings('ignore')\n"
            f"import importlib\n"
            f"m = importlib.import_module({dotted!r})\n"
            f"assert hasattr(m, 'Exploit'), 'No Exploit class'\n"
            f"print('OK')\n"
        )
        ok, out = _run_python_file(script, timeout=15)
        if not ok:
            results.append(_fail(f"import:{path.stem}", f"{path.name}: import failed: {out[:200]}"))
        else:
            results.append(_ok(f"import:{path.stem}"))
    return results


def _check_anti_false_positive(paths: List[Path]) -> List[CheckResult]:
    """Verify check() returns False/None on closed port 63994 (never True)."""
    results: List[CheckResult] = []
    for path in paths:
        if not path.exists():
            continue
        dotted = (
            "embedxpl.modules."
            + str(path.relative_to(ROOT / "embedxpl" / "modules"))
            .replace(os.sep, ".")
            .removesuffix(".py")
        )
        script = (
            f"import warnings, threading\n"
            f"warnings.filterwarnings('ignore')\n"
            f"import importlib\n"
            f"m = importlib.import_module({dotted!r})\n"
            f"cls = m.Exploit\n"
            f"e = cls.__new__(cls)\n"
            f"e.target = '127.0.0.1'\n"
            f"e.port = 63994\n"
            f"try:\n"
            f"    init = getattr(type(e), '__init__', None)\n"
            f"    if init and init is not object.__init__: init(e)\n"
            f"except Exception: pass\n"
            f"result_box = [None]\n"
            f"def _run():\n"
            f"    try: result_box[0] = e.check()\n"
            f"    except Exception: result_box[0] = False\n"
            f"t = threading.Thread(target=_run, daemon=True)\n"
            f"t.start(); t.join(timeout=8)\n"
            f"if t.is_alive():\n"
            f"    print('TIMEOUT'); exit(0)\n"
            f"result = result_box[0]\n"
            f"assert not result, f'check() returned {{result!r}} on closed port'\n"
            f"print('OK')\n"
        )
        ok, out = _run_python_file(script, timeout=15)
        if not ok and "TIMEOUT" not in out:
            results.append(_fail(f"anti_fp:{path.stem}", f"{path.name}: {out[:200]}"))
        else:
            results.append(_ok(f"anti_fp:{path.stem}"))
    return results


def _check_indexed(stems: List[str]) -> CheckResult:
    """Verify all module stems appear in index_modules() output."""
    script = (
        "from embedxpl.core.exploit.utils import index_modules\n"
        "mods = index_modules()\n"
        "print('\\n'.join(mods))\n"
    )
    ok, out = _run_python_file(script, timeout=20)
    if not ok:
        return _fail("indexed", f"index_modules() failed: {out[:200]}")
    found = out.splitlines()
    missing = [s for s in stems if not any(s in m for m in found)]
    if missing:
        return _fail("indexed", f"Not indexed: {missing[:5]}")
    return _ok("indexed", f"All {len(stems)} modules indexed")


def _check_flake8(paths: List[Path]) -> CheckResult:
    """Run flake8 on all paths and fail on critical errors (E1/E2/E7/W6)."""
    py_paths = [str(p) for p in paths if p.exists()]
    if not py_paths:
        return _ok("flake8", "no files to check")
    try:
        proc = subprocess.run(
            [sys.executable, "-m", "flake8",
             "--select=E1,E2,E7,W6",
             "--extend-ignore=E501",
             "--per-file-ignores=embedxpl/modules/*:F401,F403,F405,E221",
             ] + py_paths,
            capture_output=True, text=True, timeout=60, cwd=str(ROOT),
        )
        if proc.returncode != 0 and proc.stdout.strip():
            lines = proc.stdout.strip().splitlines()
            return _fail("flake8", f"{len(lines)} issues: {lines[0]}")
        return _ok("flake8")
    except FileNotFoundError:
        return _ok("flake8", "flake8 not installed, skipping")
    except Exception as e:
        return _fail("flake8", str(e))


def _check_total_module_count(expected_min: int) -> CheckResult:
    script = (
        "from embedxpl.core.exploit.utils import index_modules\n"
        "mods = index_modules()\n"
        f"assert len(mods) >= {expected_min}, f'Only {{len(mods)}} modules, expected >={expected_min}'\n"
        "print(len(mods))\n"
    )
    ok, out = _run_python_file(script, timeout=20)
    if not ok:
        return _fail("total_module_count", out[:200])
    return _ok("total_module_count", f"{out} modules indexed (min {expected_min})")


# ─── Gate: A1A2 ───────────────────────────────────────────────────────────────

_TRACK_A1_PATHS = [
    ROOT / "embedxpl/modules/exploits/printers/generic/edb_15631_pjl_unrestricted_access.py",
    ROOT / "embedxpl/modules/exploits/printers/generic/edb_22319_hp_snmp_info_disclosure.py",
    ROOT / "embedxpl/modules/exploits/printers/generic/edb_45205_generic_printer_rce.py",
    ROOT / "embedxpl/modules/exploits/printers/generic/edb_50498_lexmark_stored_xss.py",
    ROOT / "embedxpl/modules/exploits/printers/generic/edb_51606_hp_ssrf_cve_2021_3441.py",
    ROOT / "embedxpl/modules/exploits/printers/generic/edb_51928_ricoh_auth_bypass.py",
    ROOT / "embedxpl/modules/exploits/printers/generic/samsung_cve_2016_11061_xxe.py",
    ROOT / "embedxpl/modules/exploits/printers/xerox/xerox_cve_2023_3710_workcentre_rce.py",
]

_TRACK_A2_PATHS = [
    ROOT / "embedxpl/modules/exploits/printers/hp/hp_laserjet_pjl_scan_native.py",
    ROOT / "embedxpl/modules/exploits/printers/hp/hp_laserjet_snmp_community_enum.py",
    ROOT / "embedxpl/modules/exploits/printers/canon/canon_driver_privesc_cve_2021_38085.py",
]

_TRACK_A1A2_ALL = _TRACK_A1_PATHS + _TRACK_A2_PATHS


def gate_A1A2() -> List[CheckResult]:
    results = _common_module_checks(_TRACK_A1A2_ALL)
    results += _check_importable(_TRACK_A1A2_ALL)
    results += _check_anti_false_positive(_TRACK_A1A2_ALL)
    results.append(_check_flake8(_TRACK_A1A2_ALL))
    results.append(_check_indexed([p.stem for p in _TRACK_A1A2_ALL]))
    results.append(_check_total_module_count(BASELINE_MODULE_COUNT + 11))
    return results


# ─── Gate: B ──────────────────────────────────────────────────────────────────

_TRACK_B_PATHS = [
    ROOT / "embedxpl/modules/exploits/embedded_os/gnu_inetutils_telnetd_auth_bypass_cve_2026_24061.py",
    ROOT / "embedxpl/modules/exploits/printers/linux/cups_pwn2own_stage1_cve_2026_34477.py",
    ROOT / "embedxpl/modules/exploits/printers/linux/cups_pwn2own_stage2_cve_2026_34478.py",
    ROOT / "embedxpl/modules/exploits/printers/linux/cups_pwn2own_stage3_cve_2026_34479.py",
    ROOT / "embedxpl/modules/exploits/printers/linux/cups_pwn2own_chain_cve_2026_34480.py",
    ROOT / "embedxpl/modules/exploits/routers/generic/cve_2026_31602_unauth_rce.py",
    ROOT / "embedxpl/modules/exploits/embedded_os/cve_2026_40683_embedded_rce.py",
    ROOT / "embedxpl/modules/exploits/routers/generic/cve_2026_22812_cmd_injection.py",
    ROOT / "embedxpl/modules/exploits/embedded_os/cve_2026_0234_auth_bypass.py",
    ROOT / "embedxpl/modules/exploits/embedded_os/cve_2026_21513_privesc.py",
    ROOT / "embedxpl/modules/exploits/embedded_os/cve_2026_21519_rce.py",
]


def _check_cvss_present(paths: List[Path]) -> CheckResult:
    """Verify __info__['cvss'] is present and non-empty in all paths."""
    bad = []
    for path in paths:
        if not path.exists():
            continue
        src = _read_file(path)
        if '"cvss"' not in src and "'cvss'" not in src:
            bad.append(path.name)
    if bad:
        return _fail("cvss_present", f"Missing 'cvss' in __info__: {bad}")
    return _ok("cvss_present")


def _check_cups_chain_calls_stages(chain_path: Path) -> CheckResult:
    """Verify the CUPS chain module instantiates and calls other stages."""
    if not chain_path.exists():
        return _fail("cups_chain_stages", f"Chain file not found: {chain_path}")
    src = _read_file(chain_path)
    run_calls = re.findall(r"\.run\(\)", src)
    if len(run_calls) < 2:
        return _fail("cups_chain_stages", f"cups_pwn2own_chain: only {len(run_calls)} .run() calls, expected >=2")
    return _ok("cups_chain_stages", f"{len(run_calls)} .run() calls confirmed")


def gate_B() -> List[CheckResult]:
    results = _common_module_checks(_TRACK_B_PATHS)
    results += _check_importable(_TRACK_B_PATHS)
    results += _check_anti_false_positive(_TRACK_B_PATHS)
    results.append(_check_cvss_present(_TRACK_B_PATHS))
    results.append(_check_cups_chain_calls_stages(
        ROOT / "embedxpl/modules/exploits/printers/linux/cups_pwn2own_chain_cve_2026_34480.py"
    ))
    results.append(_check_flake8(_TRACK_B_PATHS))
    results.append(_check_indexed([p.stem for p in _TRACK_B_PATHS]))
    results.append(_check_total_module_count(BASELINE_MODULE_COUNT + 22))
    return results


# ─── Gate: C ──────────────────────────────────────────────────────────────────

_TRACK_C_PATHS = [
    ROOT / "embedxpl/modules/exploits/embedded_os/wolfssl_identity_forgery_cve_2026_5194.py",
    ROOT / "embedxpl/modules/exploits/firewalls/paloalto/panos_userid_bof_rce_cve_2026_0300.py",
    ROOT / "embedxpl/modules/exploits/ics/ur_polyscope5_dashboard_cmd_injection_cve_2026_8153.py",
    ROOT / "embedxpl/modules/exploits/embedded_os/riot_sixlowpan_oob_read_cve_2026_25139.py",
    ROOT / "embedxpl/modules/exploits/smart_home/enet_smarthome_default_creds_cve_2026_26366.py",
    ROOT / "embedxpl/modules/exploits/specialized/metis_wic_unauth_rce_cve_2026_2248.py",
    ROOT / "embedxpl/modules/exploits/specialized/metis_dfs_unauth_rce_cve_2026_2249.py",
    ROOT / "embedxpl/modules/exploits/smart_home/openremote_expr_injection_rce_cve_2026_39842.py",
    ROOT / "embedxpl/modules/exploits/routers/totolink/a7000r_cmd_injection_cve_2026_1623.py",
    ROOT / "embedxpl/modules/exploits/embedded_os/rauc_integer_overflow_cve_2026_34155.py",
    ROOT / "embedxpl/modules/exploits/routers/generic/openwrt_hotplug_privesc_cve_2026_30874.py",
    ROOT / "embedxpl/modules/exploits/embedded_os/tuya_arduino_dns_bof_cve_2026_28519.py",
]


def _check_bof_payload_bytes(paths: List[Path]) -> CheckResult:
    """Verify BOF modules use struct.pack or bytes literals for payload construction."""
    high_cvss_bof = [p for p in paths if any(kw in p.stem for kw in (
        "bof", "overflow", "shellz", "wolfssl", "panos_userid"
    ))]
    bad = []
    for path in high_cvss_bof:
        if not path.exists():
            continue
        src = _read_file(path)
        has_bytes = any(token in src for token in ("struct.pack", "b'\\x", 'b"\\x', "bytearray(", "bytes(["))
        if not has_bytes:
            bad.append(path.name)
    if bad:
        return _fail("bof_payload_bytes", f"Missing struct/bytes payload construction in: {bad}")
    return _ok("bof_payload_bytes")


def _check_default_creds_pairs(paths: List[Path]) -> CheckResult:
    """Verify default-creds modules iterate at least 3 pairs."""
    cred_paths = [p for p in paths if any(kw in p.stem for kw in ("creds", "default", "enet"))]
    bad = []
    for path in cred_paths:
        if not path.exists():
            continue
        src = _read_file(path)
        pairs = re.findall(r"['\"][^'\"]+:[^'\"]+['\"]", src)
        cred_pairs = [p for p in pairs if ":" in p and not p.startswith("'http") and not p.startswith('"http')]
        if len(cred_pairs) < 3:
            bad.append(f"{path.name} ({len(cred_pairs)} pairs found)")
    if bad:
        return _fail("creds_pairs", f"Fewer than 3 credential pairs in: {bad}")
    return _ok("creds_pairs")


def gate_C() -> List[CheckResult]:
    results = _common_module_checks(_TRACK_C_PATHS)
    results += _check_importable(_TRACK_C_PATHS)
    results += _check_anti_false_positive(_TRACK_C_PATHS)
    results.append(_check_cvss_present(_TRACK_C_PATHS))
    results.append(_check_bof_payload_bytes(_TRACK_C_PATHS))
    results.append(_check_default_creds_pairs(_TRACK_C_PATHS))
    results.append(_check_flake8(_TRACK_C_PATHS))
    results.append(_check_indexed([p.stem for p in _TRACK_C_PATHS]))
    results.append(_check_total_module_count(BASELINE_MODULE_COUNT + 34))
    return results


# ─── Gate: A3 ─────────────────────────────────────────────────────────────────

_TRACK_A3_PATHS = [
    ROOT / "embedxpl/modules/exploits/printers/lexmark/lexmark_heap_bof_cve_2023_50734.py",
    ROOT / "embedxpl/modules/exploits/printers/lexmark/lexmark_ps_bof_cve_2023_50736.py",
    ROOT / "embedxpl/modules/exploits/printers/lexmark/lexmark_pwn2own_2026_chain.py",
    ROOT / "embedxpl/modules/exploits/printers/ricoh/ricoh_http_bof_cve_2024_34161.py",
    ROOT / "embedxpl/modules/exploits/printers/xerox/xerox_http_bof_rce.py",
    ROOT / "embedxpl/modules/exploits/printers/xerox/xerox_ipp_bof_rce.py",
    ROOT / "embedxpl/modules/exploits/printers/hp/hp_printing_shellz_rce.py",
    ROOT / "embedxpl/modules/exploits/printers/brother/brother_ldap_smb_passback.py",
    ROOT / "embedxpl/modules/exploits/printers/brother/brother_wsd_dos.py",
    ROOT / "embedxpl/modules/exploits/printers/brother/brother_wsd_ssrf.py",
    ROOT / "embedxpl/modules/exploits/printers/canon/canon_xps_bof_cve_2025_14237.py",
    ROOT / "embedxpl/modules/exploits/printers/generic/ipp_anon_print_inject.py",
    ROOT / "embedxpl/modules/exploits/printers/generic/ipp_purge_jobs_dos.py",
    ROOT / "embedxpl/modules/exploits/printers/generic/ms_rprn_ntlm_coerce.py",
    ROOT / "embedxpl/modules/exploits/printers/generic/pjl_pwd_disclosure_cve_2011_4786.py",
    ROOT / "embedxpl/modules/exploits/printers/generic/ps_infinite_loop_dos.py",
    ROOT / "embedxpl/modules/exploits/printers/generic/tftp_loop_dos.py",
    ROOT / "embedxpl/modules/exploits/printers/generic/wsd_printer_enum.py",
    ROOT / "embedxpl/modules/exploits/printers/generic/ssport_lpe.py",
    ROOT / "embedxpl/modules/exploits/printers/hp/hp_fw_sig_bypass.py",
]


def _check_bof_no_string_padding(paths: List[Path]) -> CheckResult:
    """Verify BOF modules don't use 'A'*N as payload string."""
    bof_paths = [p for p in paths if "bof" in p.stem or "shellz" in p.stem]
    bad = []
    for path in bof_paths:
        if not path.exists():
            continue
        src = _read_file(path)
        if re.search(r"[\"'][A-Za-z][\"']\s*\*\s*\d+", src):
            bad.append(path.name)
    if bad:
        return _fail("bof_no_string_padding", f"String padding payload (use struct/bytes instead): {bad}")
    return _ok("bof_no_string_padding")


def _check_chain_calls_runs(chain_path: Path) -> CheckResult:
    """Verify a chain module calls .run() on at least 2 stage instances."""
    if not chain_path.exists():
        return _fail("chain_stages", f"Chain not found: {chain_path}")
    src = _read_file(chain_path)
    run_calls = re.findall(r"\.run\(\)", src)
    if len(run_calls) < 2:
        return _fail("chain_stages", f"{chain_path.name}: only {len(run_calls)} .run() calls, expected >=2")
    return _ok("chain_stages")


def _check_passback_no_hardcoded_ip(paths: List[Path]) -> CheckResult:
    """Verify passback/coerce modules use OptString for attacker address."""
    passback_paths = [p for p in paths if any(kw in p.stem for kw in ("passback", "coerce", "ntlm"))]
    bad = []
    for path in passback_paths:
        if not path.exists():
            continue
        src = _read_file(path)
        # Should use OptString for attacker address, not hardcode IP
        has_opt = "OptString" in src and ("attacker" in src or "unc" in src.lower() or "listener" in src)
        if not has_opt:
            bad.append(path.name)
    if bad:
        return _fail("passback_no_hardcoded_ip", f"Passback module missing OptString for attacker address: {bad}")
    return _ok("passback_no_hardcoded_ip")


def gate_A3() -> List[CheckResult]:
    results = _common_module_checks(_TRACK_A3_PATHS)
    results += _check_importable(_TRACK_A3_PATHS)
    results += _check_anti_false_positive(_TRACK_A3_PATHS)
    results.append(_check_bof_payload_bytes(_TRACK_A3_PATHS))
    results.append(_check_bof_no_string_padding(_TRACK_A3_PATHS))
    results.append(_check_chain_calls_runs(
        ROOT / "embedxpl/modules/exploits/printers/lexmark/lexmark_pwn2own_2026_chain.py"
    ))
    results.append(_check_passback_no_hardcoded_ip(_TRACK_A3_PATHS))
    results.append(_check_flake8(_TRACK_A3_PATHS))
    results.append(_check_indexed([p.stem for p in _TRACK_A3_PATHS]))
    results.append(_check_total_module_count(BASELINE_MODULE_COUNT + 51))
    return results


# ─── Gate: D ──────────────────────────────────────────────────────────────────

_TRACK_D_PATHS = [
    ROOT / "embedxpl/modules/exploits/routers/cisco/ios_xe_wlc_jwt_rce_cve_2025_20188.py",
    ROOT / "embedxpl/modules/exploits/routers/engenius/ews356_blind_cmd_injection_cve_2024_36061.py",
    ROOT / "embedxpl/modules/exploits/routers/engenius/enstation5_cmd_injection_cve_2024_31976.py",
]


def _check_cisco_jwt_constant(path: Path) -> CheckResult:
    """Verify the Cisco module has a real JWT constant, not a generic placeholder."""
    if not path.exists():
        return _fail("cisco_jwt", f"File not found: {path}")
    src = _read_file(path)
    # Generic placeholders that indicate incomplete implementation
    placeholders = ("JWT_HERE", "YOUR_JWT_HERE", "INSERT_JWT", "PUT_JWT_HERE")
    for ph in placeholders:
        if ph in src:
            return _fail("cisco_jwt", f"JWT generic placeholder '{ph}' still present")
    # Must contain an actual eyJ... JWT structure (the CVE hardcoded value)
    has_jwt = ("eyJ" in src and "." in src) or "Bearer" in src or "jwt" in src.lower()
    if not has_jwt:
        return _fail("cisco_jwt", "No JWT token reference found in ios_xe_wlc module")
    return _ok("cisco_jwt")


def _check_engenius_blind_injection(paths: List[Path]) -> CheckResult:
    """Verify EnGenius modules use time-based or OOB blind injection."""
    engenius = [p for p in paths if "engenius" in str(p) or "ews356" in p.stem or "enstation5" in p.stem]
    bad = []
    for path in engenius:
        if not path.exists():
            continue
        src = _read_file(path)
        has_blind = (
            "time.sleep" in src
            or "attacker_ip" in src
            or "OOB" in src
            or "time_based" in src
            or "delta" in src
        )
        if not has_blind:
            bad.append(path.name)
    if bad:
        return _fail("blind_injection", f"Missing time-based or OOB mechanism in: {bad}")
    return _ok("blind_injection")


def gate_D() -> List[CheckResult]:
    results = _common_module_checks(_TRACK_D_PATHS)
    results += _check_importable(_TRACK_D_PATHS)
    results += _check_anti_false_positive(_TRACK_D_PATHS)
    results.append(_check_cvss_present(_TRACK_D_PATHS))
    results.append(_check_cisco_jwt_constant(
        ROOT / "embedxpl/modules/exploits/routers/cisco/ios_xe_wlc_jwt_rce_cve_2025_20188.py"
    ))
    results.append(_check_engenius_blind_injection(_TRACK_D_PATHS))
    results.append(_check_flake8(_TRACK_D_PATHS))
    results.append(_check_indexed([p.stem for p in _TRACK_D_PATHS]))
    results.append(_check_total_module_count(BASELINE_MODULE_COUNT + 54))
    return results


# ─── Gate: E ──────────────────────────────────────────────────────────────────

_ALL_NEW_PATHS = (
    _TRACK_A1A2_ALL
    + _TRACK_B_PATHS
    + _TRACK_C_PATHS
    + _TRACK_A3_PATHS
    + _TRACK_D_PATHS
)


def _check_no_stubs_in_all() -> CheckResult:
    """Verify zero TODO/FIXME/PLACEHOLDER/raise NotImplementedError in any new module."""
    bad = []
    for path in _ALL_NEW_PATHS:
        if not path.exists():
            continue
        src = _read_file(path)
        for pattern in ("TODO", "FIXME", "PLACEHOLDER", "raise NotImplementedError", "pass  #"):
            if pattern in src:
                bad.append(f"{path.name}:{pattern}")
    if bad:
        return _fail("no_stubs", f"Prohibited stubs in: {bad[:5]}")
    return _ok("no_stubs", "Zero stubs/placeholders in all new modules")


def _check_references_have_urls() -> CheckResult:
    """Verify every new module has at least one URL in references."""
    bad = []
    known_url_domains = ("nvd.nist.gov", "exploit-db.com", "github.com",
                         "packetstormsecurity.com", "cve.mitre.org",
                         "rapid7.com", "sploitus.com", "attackerkb.com")
    for path in _ALL_NEW_PATHS:
        if not path.exists():
            continue
        src = _read_file(path)
        ref_m = re.search(r"['\"]references['\"][^(]*\((.*?)\)", src, re.S)
        if ref_m:
            ref_block = ref_m.group(1)
            has_url = any(d in ref_block for d in known_url_domains)
            if not has_url:
                bad.append(path.name)
        else:
            bad.append(path.name)
    if bad:
        return _fail("references_urls", f"Missing known-source URL in references: {bad[:5]}")
    return _ok("references_urls", f"All {len(_ALL_NEW_PATHS)} modules have source URLs")


def _check_changelog_updated() -> CheckResult:
    changelog = ROOT / "CHANGELOG.md"
    if not changelog.exists():
        return _fail("changelog", "CHANGELOG.md not found")
    content = changelog.read_text(encoding="utf-8", errors="replace")
    required = ["CVE-2026-24061", "CVE-2025-20188"]
    missing = [c for c in required if c not in content]
    if missing:
        return _fail("changelog", f"CHANGELOG missing: {missing}")
    return _ok("changelog", "CHANGELOG.md updated with new CVEs")


def gate_E() -> List[CheckResult]:
    results: List[CheckResult] = []
    results.append(_check_no_stubs_in_all())
    results.append(_check_references_have_urls())
    results.append(_check_changelog_updated())
    results.append(_check_total_module_count(BASELINE_MODULE_COUNT + 54))
    return results


# ─── Gate: Final ──────────────────────────────────────────────────────────────

def gate_final_new() -> List[CheckResult]:
    results: List[CheckResult] = []
    results.append(_check_total_module_count(BASELINE_MODULE_COUNT + 54))

    # Announcement files
    ann = ROOT / "docs" / "ANNOUNCEMENT.md"
    ann_short = ROOT / "docs" / "ANNOUNCEMENT_SHORT.md"
    if not ann.exists() or ann.stat().st_size < 500:
        results.append(_fail("announcement", f"docs/ANNOUNCEMENT.md missing or too short ({ann.stat().st_size if ann.exists() else 0} bytes)"))
    else:
        results.append(_ok("announcement", f"ANNOUNCEMENT.md: {ann.stat().st_size} bytes"))

    if not ann_short.exists() or ann_short.stat().st_size < 100:
        results.append(_fail("announcement_short", "docs/ANNOUNCEMENT_SHORT.md missing or too short"))
    else:
        results.append(_ok("announcement_short"))

    # No em-dash or AI markers in new py/md files
    em_dash = "\u2014"
    ai_markers = ("generated by", "created with AI", "AI note", "LLM suggestion")
    bad_files = []
    for path in _ALL_NEW_PATHS:
        if not path.exists():
            continue
        content = _read_file(path)
        if em_dash in content:
            bad_files.append(f"{path.name}:em-dash")
        for marker in ai_markers:
            if marker.lower() in content.lower():
                bad_files.append(f"{path.name}:AI-marker")
    if bad_files:
        results.append(_fail("prohibited_content", f"Prohibited content in: {bad_files[:5]}"))
    else:
        results.append(_ok("prohibited_content", "No em-dash or AI markers in new modules"))

    # Changelog
    results.append(_check_changelog_updated())

    # Git clean
    try:
        proc = subprocess.run(
            ["git", "status", "--porcelain"],
            capture_output=True, text=True, timeout=10, cwd=str(ROOT),
        )
        if proc.stdout.strip():
            results.append(_fail("git_clean", f"Working tree not clean: {proc.stdout.strip()[:100]}"))
        else:
            results.append(_ok("git_clean", "Working tree clean"))
    except Exception as e:
        results.append(_fail("git_clean", str(e)))

    return results


# ─── Gate runner ──────────────────────────────────────────────────────────────

_GATE_REGISTRY = {
    "A1A2": gate_A1A2,
    "B": gate_B,
    "C": gate_C,
    "A3": gate_A3,
    "D": gate_D,
    "E": gate_E,
    "final": gate_final_new,
}


def _print_result(r: CheckResult) -> None:
    mark = "\033[92m PASS \033[0m" if r.passed else "\033[91m FAIL \033[0m"
    label = r.name[:40].ljust(42)
    msg = f"  {r.message[:90]}" if r.message else ""
    print(f"  [{mark}] {label}{msg}")


def run_gate(name: str) -> bool:
    fn = _GATE_REGISTRY.get(name)
    if fn is None:
        print(f"Unknown gate: {name}")
        return False
    print(f"\n\033[1m\033[96m{'='*60}\033[0m")
    print(f"\033[1m\033[96m  GATE {name}\033[0m")
    print(f"\033[1m\033[96m{'='*60}\033[0m")
    results = fn()
    passed = sum(1 for r in results if r.passed)
    total = len(results)
    for r in results:
        _print_result(r)
    print(f"\n\033[1mResults: {passed}/{total} passed\033[0m", end="  ")
    if passed == total:
        print(f"\033[92m(all passed)\033[0m")
        print(f"\n\033[92m\033[1mGate {name} PASSED.\033[0m\n")
        return True
    else:
        failed = [r.name for r in results if not r.passed]
        print(f"\033[91m(FAILED: {failed[:5]})\033[0m")
        print(f"\n\033[91m\033[1mGate {name} FAILED. Fix all issues before proceeding.\033[0m\n")
        return False


def main() -> None:
    parser = argparse.ArgumentParser(description="EmbedXPL-Forge Quality Gates")
    parser.add_argument("--phase", metavar="N",
                        help=f"Run specific gate: {', '.join(_GATE_REGISTRY)}")
    parser.add_argument("--all", action="store_true", help="Run all gates in order")
    parser.add_argument("--list", action="store_true", help="List available gates")
    args = parser.parse_args()

    if args.list:
        print("\n\033[1mAvailable Gates:\033[0m")
        for name in _GATE_REGISTRY:
            print(f"  --phase {name:<12} Gate {name}")
        return

    if args.all:
        all_passed = True
        for name in _GATE_REGISTRY:
            if not run_gate(name):
                all_passed = False
                print(f"\033[91mGate {name} failed. Stopping.\033[0m")
                sys.exit(1)
        if all_passed:
            print("\033[92m\033[1mAll gates PASSED.\033[0m")
        sys.exit(0 if all_passed else 1)

    if args.phase:
        success = run_gate(args.phase)
        sys.exit(0 if success else 1)

    parser.print_help()


if __name__ == "__main__":
    main()
